### ISSUE TITLE
Unknown joints in murml-description cause Exception in ASAPrealizer

### ISSUE THREAD

**Issue by herwinvw** [ArticulatedSocialAgentsPlatform/AsapRealizer#115]
The following BML contains a joint that is not present in Billie (whyever that may be in the first place...):

<bml xmlns="http://www.bml-initiative.org/bml/bml-1.0"  id="bml4" >
<murmlgesture id="gesture1" start="0" xmlns="http://www.techfak.uni-bielefeld.de/ags/soa/murml">
	<murml-description>
		<dynamic>
		<keyframing mode="spline" easescale="1.0" easeturningpoint="0.5" >
			<phase>
			<frame ftime="0.50"><posture>Humanoid (vt6 3 0.0 0.0 -5.0)</posture></frame>
			</phase>
		</keyframing>
		</dynamic>
	</murml-description>
</murmlgesture>
</bml> 

When sent, it causes this Exception (instead of providing just a warning):

     [java] Exception in thread "DefaultPhysicsEnvironmentClock" java.lang.NullPointerException
     [java] 	at asap.animationengine.keyframe.MURMLKeyframeMU.getStartKeyFrame(MURMLKeyframeMU.java:165)
     [java] 	at asap.motionunit.keyframe.KeyFrameMotionUnit.setupDynamicStart(KeyFrameMotionUnit.java:59)
     [java] 	at asap.animationengine.keyframe.MURMLKeyframeMU.startUnit(MURMLKeyframeMU.java:174)
     [java] 	at asap.motionunit.TimedMotionUnit.startUnit(TimedMotionUnit.java:135)
     [java] 	at asap.realizer.planunit.TimedAbstractPlanUnit.start(TimedAbstractPlanUnit.java:223)
     [java] 	at asap.realizer.planunit.DefaultTimedPlanUnitPlayer.playUnit(DefaultTimedPlanUnitPlayer.java:26)
     [java] 	at asap.animationengine.AnimationPlanPlayer.playback(AnimationPlanPlayer.java:148)
     [java] 	at asap.animationengine.AnimationPlanPlayer.play(AnimationPlanPlayer.java:125)
     [java] 	at asap.animationengine.AnimationPlayer.playKinematics(AnimationPlayer.java:466)
     [java] 	at asap.animationengine.AnimationPlayer.playStep(AnimationPlayer.java:302)
     [java] 	at hmi.mixedanimationenvironment.MixedAnimationPlayerManager.time(MixedAnimationPlayerManager.java:133)
     [java] 	at hmi.mixedanimationenvironment.MixedAnimationEnvironment.physicsUpdate(MixedAnimationEnvironment.java:89)
     [java] 	at hmi.physicsenvironment.OdePhysicsEnvironment.physicsTime(OdePhysicsEnvironment.java:602)
     [java] 	at hmi.physicsenvironment.OdePhysicsEnvironment$MyPhysicsClockListener.time(OdePhysicsEnvironment.java:277)
     [java] 	at hmi.util.SystemClock.time(SystemClock.java:282)
     [java] 	at hmi.util.SystemClock.access$400(SystemClock.java:53)
     [java] 	at hmi.util.SystemClock$ClockThread.run(SystemClock.java:313)

**Comment by herwinvw** [comment]
_Imported from trac issue 115.  Created by yaghoubzadeh on 2014-01-23T15:04:07, last modified: 2014-01-31T15:03:05_

**Comment by herwinvw** [comment]
_Trac comment by yaghoubzadeh on 2014-01-23 15:16:08:_

Addition: I got the Exception with these emitters turned on beforehand:

<bml xmlns="http://www.bml-initiative.org/bml/bml-1.0" xmlns:bmlt="http://hmi.ewi.utwente.nl/bmlt" xmlns:bmla="http://www.asap-project.org/bmla" id="bml1">
<bmlt:blinkemitter id="blinkemitter1" start="0" range="0.5" avgwaitingtime="3.5"/>
<bmlt:breathingemitter id="breathingemitter1" start="0" range="2" avgwaitingtime="3.5"/>
</bml>

**Comment by herwinvw** [comment]
_Trac comment by welberge on 2014-01-30 16:24:46:_

Should be fixed, tested with unit test, to test in realizer itself.
