### ISSUE TITLE
Duplicate stop feedback

### ISSUE THREAD

**Issue by herwinvw** [ArticulatedSocialAgentsPlatform/AsapRealizer#118]
Occurs every now and then in testInterrupt in !PersistentFixtureAsapRealizerTest:
{{{
[junit] Testcase: testInterrupt(asap.realizertester.PersistentFixtureAsapRealizerTest):	FAILED
    [junit] Duplicate stopfeedback: Performance Stop of bml1 at 82.96236419677734
    [junit] List:[Performance Stop of bml1 at 82.96236419677734
    [junit] , Performance Stop of bml1 at 82.96236419677734
    [junit] , Performance Stop of bml2 at 82.96236419677734
    [junit] ]
    [junit] junit.framework.AssertionFailedError: Duplicate stopfeedback: Performance Stop of bml1 at 82.96236419677734
    [junit] List:[Performance Stop of bml1 at 82.96236419677734
    [junit] , Performance Stop of bml1 at 82.96236419677734
    [junit] , Performance Stop of bml2 at 82.96236419677734
    [junit] ]
    [junit] 	at bml.realizertest.BMLRealizerHandler.assertNoDuplicateStop(BMLRealizerHandler.java:329)
    [junit] 	at bml.realizertest.BMLRealizerHandler.assertNoDuplicateFeedbacks(BMLRealizerHandler.java:380)
    [junit] 	at asap.realizertester.AbstractASAPRealizerTest.testInterrupt(AbstractASAPRealizerTest.java:218)
    [junit] 	at hmi.testutil.rules.FailOnTimeoutWithCallback$1.run(FailOnTimeoutWithCallback.java:40)
    [junit] 
    [junit] 
}}}

**Comment by herwinvw** [comment]
_Imported from trac issue 118.  Created by welberge on 2014-02-04T09:49:14, last modified: 2014-02-21T09:57:12_

**Comment by herwinvw** [comment]
_Trac comment by welberge on 2014-02-21 09:57:12:_

Should be fixed, close if it doesn't occur again.
