### ISSUE TITLE
Better error description for failing renaming files in IpaacaFaceAndBodyEmbodimentLoader

### ISSUE THREAD

**Issue by herwinvw** [ArticulatedSocialAgentsPlatform/AsapRealizer#64]
Currently it's:
[java] Exception in thread "main" java.lang.NullPointerException
     [java]  at java.io.Reader.<init>(Reader.java:78)
     [java]  at
     java.io.InputStreamReader.<init>(InputStreamReader.java:72)
     [java]  at hmi.xml.XMLTokenizer.<init>(XMLTokenizer.java:131)
     [java]  at
     asap.ipaacaembodiments.loader.IpaacaFaceAndBodyEmbodimentLoader.getRenamingMap(IpaacaFaceAndBodyEmbodimentLoader.java:84)

**Comment by herwinvw** [comment]
_Imported from trac issue 64.  Created by welberge on 2013-05-14T16:57:58, last modified: 2013-08-23T17:03:41_
